title: カイロプラクティック ひだまり
lang: ja
url: https://www.hidamari-chiro.jp
permalink: /blog/:year:month:day.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - CLAUDE.md
  - files.zip
  - "hidamari_project_log*.md"
  - .claude
  - .gitignore
  - vendor
