backend:
  name: github
  repo: TestTeston/hidamari-chiro
  branch: main

locale: ja

media_folder: blog/images
public_folder: /blog/images

collections:
  - name: posts
    label: ブログ記事
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: タイトル
        name: title
        widget: string
      - label: 投稿日
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
      - label: カテゴリ
        name: category
        widget: select
        options:
          - お知らせ
          - 日常
          - 健康コラム
          - 症状について
        default: お知らせ
      - label: アイキャッチ画像
        name: image
        widget: image
        required: false
      - label: 本文
        name: body
        widget: markdown
